const categories = [
  { name: "Akademik" },
  { name: "Beasiswa" },
  { name: "Kegiatan Kampus" },
  { name: "Organisasi Mahasiswa" },
  { name: "Kehidupan di Kampus" },
  { name: "Lowongan Kerja & Magang" },
  { name: "Event & Seminar" },
  { name: "Teknologi & Startup" },
  { name: "Hiburan & Hobi" },
  { name: "Olahraga" },
  { name: "Kesehatan Mental & Fisik" },
  { name: "Akomodasi & Kos" },
  { name: "Jual Beli Barang Mahasiswa" },
  { name: "Opini & Diskusi Umum" },
  { name: "Keluh Kesah Mahasiswa" },
  { name: "Tips & Trik Kuliah" },
  { name: "Bimbingan Skripsi & Tugas Akhir" },
  { name: "Materi Kuliah & Referensi" },
  { name: "Diskusi Mata Kuliah" },
  { name: "Lomba & Kompetisi" },
  { name: "Relawan & Pengabdian Masyarakat" },
  { name: "Bahasa & Literasi" },
  { name: "Sains & Riset" },
  { name: "Keuangan & Manajemen Uang" },
  { name: "Peluang Bisnis Mahasiswa" },
  { name: "Kuliner & Resep" },
  { name: "Komunitas Pecinta Buku" },
  { name: "Fotografi & Videografi" },
  { name: "Gaming & E-Sports" },
  { name: "Seni & Kreativitas" },
  { name: "Musik & Band Kampus" },
  { name: "Travel & Backpacking" },
  { name: "Pengalaman Exchange & Kuliah di Luar Negeri" },
  { name: "Diskusi Politik & Sosial" },
  { name: "Ekonomi & Bisnis" },
  { name: "Lingkungan & Keberlanjutan" },
  { name: "Crypto & Investasi" },
  { name: "Keamanan & Keselamatan Kampus" },
  { name: "Startup Mahasiswa" },
  { name: "Coding & Pengembangan Software" },
  { name: "Freelancing & Side Hustle" },
  { name: "Psikologi & Pengembangan Diri" },
  { name: "Spiritualitas & Agama di Kampus" },
  { name: "Filosofi & Pemikiran Kritis" },
  { name: "Alumni & Networking" },
  { name: "Persiapan Pascakampus" },
  { name: "Karier di Akademik & Penelitian" },
  { name: "Pendidikan & Inovasi Kurikulum" },
  { name: "Artificial Intelligence & Data Science" },
  { name: "Cybersecurity & Hacking Etis" },
  { name: "Robotika & IoT" },
  { name: "Astronomi & Ruang Angkasa" },
  { name: "Ilmu Sosial & Budaya" },
  { name: "Fiksi & Karya Sastra" },
  { name: "Film & Review" },
  { name: "Anime, Manga & Webtoon" },
  { name: "Desain Grafis & UI/UX" },
  { name: "3D Modeling & Animasi" },
  { name: "Jaringan & Infrastruktur IT" },
  { name: "Pengembangan Game" },
  { name: "Edukasi Seks & Kesehatan Reproduksi" },
  { name: "Hak & Hukum Mahasiswa" },
  { name: "Sosiologi & Antropologi" },
  { name: "Sejarah & Peradaban" },
  { name: "Matematika & Statistika" },
  { name: "Fisika & Teknik" },
  { name: "Kimia & Bioteknologi" },
  { name: "Kedokteran & Ilmu Kesehatan" },
  { name: "Farmasi & Obat-obatan" },
  { name: "Peternakan & Agribisnis" },
  { name: "Perikanan & Kelautan" },
  { name: "Arsitektur & Perencanaan Kota" },
  { name: "Transportasi & Mobilitas" },
  { name: "Astronomi & Ruang Angkasa" },
  { name: "Machine Learning & Big Data" },
  { name: "Virtual Reality & Augmented Reality" },
  { name: "Podcasting & Konten Kreator" },
  { name: "Stand Up Comedy & Humor" },
  { name: "Pendidikan Anak & Remaja" },
  { name: "Pengaruh Media Sosial" },
  { name: "Budaya Pop & Tren" },
  { name: "DIY & Kerajinan Tangan" },
  { name: "E-commerce & Marketplace" },
  { name: "Automotif & Modifikasi Kendaraan" },
  { name: "Energi Terbarukan & Teknologi Hijau" },
  { name: "Teknik Sipil & Konstruksi" },
  { name: "Keamanan Siber & Forensik Digital" },
  { name: "E-Sport Management & Streaming" },
  { name: "Startup & Kewirausahaan Digital" },
  { name: "Pemasaran Digital & SEO" },
  { name: "Periklanan & Branding" },
  { name: "Hubungan Internasional & Diplomasi" },
  { name: "Manajemen Acara & Event Organizer" },
  { name: "Pariwisata & Industri Kreatif" },
  { name: "Jurnalisme & Media" },
  { name: "Gaya Hidup Minimalis & Produktivitas" },
  { name: "Self-Improvement & Kebiasaan Positif" },
  { name: "Mahasiswa Difabel & Inklusivitas" },
  { name: "Karier di Perusahaan Multinasional" },
  { name: "Investasi Properti & Real Estate" },
];

module.exports = { categories };
