import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Bounce, ToastContainer } from "react-toastify";

import { cn } from "@/lib/utils";
import { config } from "@/config";
import { Providers } from "@/providers";

import "./globals.css";
import Scroll from "@/components/Scroll";
import { Modals } from "@/components/Modals";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={roboto.style} className={cn("min-w-[320px] antialiased")}>
        <NextTopLoader showSpinner={false} />
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss={false}
          draggable
          pauseOnHover={false}
          style={{
            zIndex: 999999,
          }}
          transition={Bounce}
        />
        <Scroll />

        <Providers>
          <Modals />
          {children}
        </Providers>
      </body>
    </html>
  );
}
