export interface Report {
  id: number;
  contentId: number;
  contentType: "question" | "answer" | "comment";
  content: string;
  author: string;
  authorId: number;
  reportType: string;
  reportReason: string;
  reportedBy: string;
  reportedById: number;
  status: string;
  date: string;
  context?: string;
  isHidden?: boolean;
  isDeleted?: boolean;
}

export const reports: Report[] = [
  {
    id: 1001,
    contentId: 5432,
    contentType: "question",
    content: "How do I make money fast online without working?",
    author: "FastCash123",
    authorId: 8765,
    reportType: "spam",
    reportReason:
      "This is clearly a spam post trying to promote get-rich-quick schemes",
    reportedBy: "QualityModerator",
    reportedById: 4321,
    status: "new",
    date: "2025-05-30T14:23:00Z",
    context: "This was posted in the Career Advice section",
  },
  {
    id: 1002,
    contentId: 6543,
    contentType: "answer",
    content:
      "This answer is completely wrong. The person who wrote this is an idiot who doesn't know what they're talking about.",
    author: "AngryUser42",
    authorId: 9876,
    reportType: "inappropriate",
    reportReason: "Personal attacks and rude language",
    reportedBy: "HelpfulUser99",
    reportedById: 5432,
    status: "in-review",
    date: "2025-05-29T09:15:00Z",
    context: "This was in response to a technical question about JavaScript",
  },
  {
    id: 1003,
    contentId: 7654,
    contentType: "comment",
    content:
      "Your ethnic group is known for being dishonest. I wouldn't trust this advice.",
    author: "Throwaway5555",
    authorId: 1234,
    reportType: "hate-speech",
    reportReason: "Racist comment targeting a specific ethnic group",
    reportedBy: "CommunityDefender",
    reportedById: 6543,
    status: "new",
    date: "2025-05-31T16:45:00Z",
  },
  {
    id: 1004,
    contentId: 8765,
    contentType: "question",
    content:
      "COVID-19 can be cured by drinking bleach and standing in the sun for 8 hours.",
    author: "TruthSeeker77",
    authorId: 2345,
    reportType: "misinformation",
    reportReason: "Dangerous health misinformation that could harm people",
    reportedBy: "HealthProfessional",
    reportedById: 7654,
    status: "in-review",
    date: "2025-05-28T11:30:00Z",
    context: "Posted in the Health & Wellness section",
  },
  {
    id: 1005,
    contentId: 9876,
    contentType: "answer",
    content:
      "Check out my profile for exclusive content! I can show you much more if you follow the link in my bio ;)",
    author: "NotABot123",
    authorId: 3456,
    reportType: "spam",
    reportReason: "Promotional content not related to the question",
    reportedBy: "SpamHunter",
    reportedById: 8765,
    status: "resolved",
    date: "2025-05-27T08:20:00Z",
    isHidden: true,
  },
  {
    id: 1006,
    contentId: 1234,
    contentType: "comment",
    content:
      "Your code solution won't work because you're not handling the edge cases properly.",
    author: "CodeReviewer",
    authorId: 4567,
    reportType: "other",
    reportReason: "This is not actually a problem, just constructive criticism",
    reportedBy: "SensitiveUser",
    reportedById: 9876,
    status: "rejected",
    date: "2025-05-26T13:10:00Z",
    context: "Comment on a programming solution",
  },
  {
    id: 1007,
    contentId: 2345,
    contentType: "question",
    content: "How do I hack into my ex's social media accounts?",
    author: "RevengeSeeker",
    authorId: 5678,
    reportType: "inappropriate",
    reportReason: "Asking for help with illegal activities",
    reportedBy: "SecurityMinded",
    reportedById: 1234,
    status: "resolved",
    date: "2025-05-25T17:05:00Z",
    isDeleted: true,
  },
  {
    id: 1008,
    contentId: 3456,
    contentType: "answer",
    content:
      "The government is tracking us through vaccines. Don't get vaccinated if you value your freedom!",
    author: "TruthExposer",
    authorId: 6789,
    reportType: "misinformation",
    reportReason: "Spreading conspiracy theories and health misinformation",
    reportedBy: "ScienceFan",
    reportedById: 2345,
    status: "new",
    date: "2025-05-31T10:40:00Z",
    context: "Answer to a question about vaccine safety",
  },
  {
    id: 1009,
    contentId: 4567,
    contentType: "comment",
    content:
      "I completely disagree with your approach. Have you considered using a different algorithm?",
    author: "AlgorithmExpert",
    authorId: 7890,
    reportType: "other",
    reportReason: "I don't like this person's tone",
    reportedBy: "EasilyOffended",
    reportedById: 3456,
    status: "rejected",
    date: "2025-05-24T15:30:00Z",
    context: "Technical discussion about sorting algorithms",
  },
  {
    id: 1010,
    contentId: 5678,
    contentType: "question",
    content:
      "What's the best way to optimize my database queries for this specific use case?",
    author: "DBOptimizer",
    authorId: 8901,
    reportType: "spam",
    reportReason: "This user keeps asking similar questions",
    reportedBy: "PatternSpotter",
    reportedById: 4567,
    status: "in-review",
    date: "2025-05-30T09:55:00Z",
    context: "Posted in Database Performance section",
  },
  {
    id: 1011,
    contentId: 6789,
    contentType: "answer",
    content:
      "You should just copy and paste code from Stack Overflow, that's what everyone does.",
    author: "QuickCoder",
    authorId: 9012,
    reportType: "misinformation",
    reportReason: "Encouraging plagiarism and bad practices",
    reportedBy: "EthicalDev",
    reportedById: 7891,
    status: "new",
    date: "2025-06-01T08:10:00Z",
    context: "Answer to a question about coding best practices",
  },
  {
    id: 1012,
    contentId: 7890,
    contentType: "comment",
    content: "You're such a noob, maybe programming isn't for you.",
    author: "ToxicUser",
    authorId: 3457,
    reportType: "inappropriate",
    reportReason: "Insulting and discouraging language",
    reportedBy: "SupportiveMember",
    reportedById: 2346,
    status: "in-review",
    date: "2025-06-01T09:20:00Z",
    context: "Comment on a beginner's question",
  },
  {
    id: 1013,
    contentId: 8901,
    contentType: "question",
    content: "Where can I download pirated software for free?",
    author: "PirateHunter",
    authorId: 4568,
    reportType: "illegal-content",
    reportReason: "Requesting illegal downloads",
    reportedBy: "LawfulUser",
    reportedById: 5679,
    status: "new",
    date: "2025-06-01T10:30:00Z",
    context: "Posted in Software section",
  },
  {
    id: 1014,
    contentId: 9012,
    contentType: "answer",
    content: "Just ignore the documentation, it's useless anyway.",
    author: "DocHater",
    authorId: 6780,
    reportType: "misinformation",
    reportReason: "Discouraging proper learning practices",
    reportedBy: "DocLover",
    reportedById: 7892,
    status: "resolved",
    date: "2025-06-01T11:45:00Z",
    context: "Answer to a question about learning resources",
  },
  {
    id: 1015,
    contentId: 9123,
    contentType: "comment",
    content: "I can help you cheat on your exams, DM me for details.",
    author: "CheatMaster",
    authorId: 8902,
    reportType: "inappropriate",
    reportReason: "Offering to help cheat",
    reportedBy: "HonestStudent",
    reportedById: 9013,
    status: "in-review",
    date: "2025-06-01T12:55:00Z",
    context: "Comment on an education-related post",
  },
];
